---
title: "data_analysis_oddball_leap_280423"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}

#chunk options
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) #warning to false


#required packages
require(lme4) #linear mixed models
require(lmerTest) #p-value for fixed effects in LMM
require(emmeans) #estimated marginalized means
require(performance) #r²_nakagawa - marginalized and conditionalk R² 

require(kableExtra) #APA tables

library(greta) #Bayesian modelling
require(bayesplot) #plotting Bayesian
require(DiagrammeR) #plotting Bayesian
require(ggplot2) #plot posterior sampling estimates

require(R.matlab) # read matlab files
require(effectsize) # cohens D

require(RColorBrewer) #color palettes
require(gridExtra) #arrange plots
require(wesanderson) #custom color palettes
  
      


##define parameters of posterior sampling in Bayesian modeling
number_of_warmups <- 1000
number_of_iterations <- 2000

project_path<-"C:/Users/nico/PowerFolders/project_oddball_LEAP"

###graphic settings

  #graphic parameters
  theme_set(theme_bw())
  
  #define color palette
  custom_condition_colors <- wes_palette('FantasticFox1',5,type='discrete')[2:5]
  custom_contrast_colors <- c(brewer.pal(6, "Blues")[4:6],brewer.pal(6, "Oranges")[4:6])
 
  #RColorBrewer::display.brewer.all()

```

```{r load_data}
load(file=paste0(project_path,'/data/mmn_leap_pd_final_dfs_21022023'))

```

# descriptives table

```{r samples description}

#### sample descriptives - PARTICIPANT specific ####

fun_return_descriptive<-function(variable,group,rounding=2,scaling=1){
  mean_values<-by(variable,group,function(x){round(mean(x,na.rm=T),rounding)})
  sd_values<-by(variable,group,function(x){round(sd(x,na.rm=T),rounding)})
  min_values<-by(variable,group,function(x){round(min(x,na.rm=T),rounding)})
  max_values<-by(variable,group,function(x){round(max(x,na.rm=T),rounding)})
  mean_values<-mean_values*scaling
  sd_values<-sd_values*scaling
  min_values<-min_values*scaling
  max_values<-max_values*scaling
  paste0(mean_values,'/',sd_values,' ','[',min_values,'-',max_values,']')
}

#standard descriptives
n_group<-with(df_dem,by(subjects,t1_diagnosis,function(x){length(unique(x))}))
gender<-with(df_dem,by(t1_sex,t1_diagnosis,function(x){paste0(table(x)[2],'/',table(x)[1])}))
timepoints<-with(df_dem,by(timepoints,t1_diagnosis,function(x){paste0(table(x)[1],'/',table(x)[2],'/',table(x)[3])}))
age<-with(df_dem,fun_return_descriptive(variable=t1_ageyrs,group=t1_diagnosis))
iq<-with(df_dem,fun_return_descriptive(variable=t1_fsiq,group=t1_diagnosis))
piq<-with(df_dem,fun_return_descriptive(variable=t1_piq,group=t1_diagnosis))
viq<-with(df_dem,fun_return_descriptive(variable=t1_viq,group=t1_diagnosis))

#clinical variables
srs<-with(df_dem,fun_return_descriptive(variable=t1_srs_rawscore,group=t1_diagnosis))
rbs_total<-with(df_dem,fun_return_descriptive(variable=t1_rbs_total,group=t1_diagnosis))
sdq_total<-with(df_dem,fun_return_descriptive(variable=t1_sdq_total_difficulties_p,group=t1_diagnosis))
adhd_inatt<-with(df_dem,fun_return_descriptive(variable=adhd_inatt,group=t1_diagnosis))
adhd_hyper<-with(df_dem,fun_return_descriptive(variable=adhd_hyper,group=t1_diagnosis))
anx_beck<-with(df_dem,fun_return_descriptive(variable=anx_beck,group=t1_diagnosis))
dep_beck<-with(df_dem,fun_return_descriptive(variable=dep_beck,group=t1_diagnosis))

##data quality
#precision<-with(df_dem,fun_return_descriptive(variable=Precision,group=t1_diagnosis))
#accuracy<-with(df_dem,fun_return_descriptive(variable=Accuracy,group=t1_diagnosis))
#sampling_rate<-with(df_dem,by(sampling_rate,t1_diagnosis,function(x){paste0(table(x)[2],'/',table(x)[1])}))
missing_data_trial<-with(df_dem,fun_return_descriptive(variable=missing_data_trial,group=t1_diagnosis,rounding=4,scaling = 100))
sampling_rate<-with(df_timepoint,by(sampling_rate,t1_diagnosis,function(x){paste0(table(x)[2],'/',table(x)[1])}))

#et vars
center_dev_id<-with(df_dem,fun_return_descriptive(variable=center_dev,group=t1_diagnosis,rounding=4,scaling=100))
screen_dist_id<-with(df_dem,fun_return_descriptive(variable=screen_dist,group=t1_diagnosis))
pd_baseline_id<-with(df_dem,fun_return_descriptive(variable=pd_baseline,group=t1_diagnosis))
# rpd_response201_id<-with(df_dem,fun_return_descriptive(variable=rpd_response.201,group=t1_diagnosis,rounding=4,scaling=100))
# rpd_response202_id<-with(df_dem,fun_return_descriptive(variable=rpd_response.202,group=t1_diagnosis,rounding=4,scaling=100))
# rpd_response203_id<-with(df_dem,fun_return_descriptive(variable=rpd_response.203,group=t1_diagnosis,rounding=4,scaling=100))
# rpd_response204_id<-with(df_dem,fun_return_descriptive(variable=rpd_response.204,group=t1_diagnosis,rounding=4,scaling=100))
# rpd_auc201_id<-with(df_dem,fun_return_descriptive(variable=rpd_auc.201,group=t1_diagnosis,rounding=4,scaling=100))
# rpd_auc202_id<-with(df_dem,fun_return_descriptive(variable=rpd_auc.202,group=t1_diagnosis,rounding=4,scaling=100))
# rpd_auc203_id<-with(df_dem,fun_return_descriptive(variable=rpd_auc.203,group=t1_diagnosis,rounding=4,scaling=100))
# rpd_auc204_id<-with(df_dem,fun_return_descriptive(variable=rpd_auc.204,group=t1_diagnosis,rounding=4,scaling=100))


rpd_auc_id<-with(df_dem,fun_return_descriptive(variable=rpd_auc,group=t1_diagnosis,rounding=4,scaling=100))


descriptives_table<-rbind(n_group,gender,timepoints,age,iq,piq,viq,
                          missing_data_trial,sampling_rate,
                          center_dev_id,screen_dist_id,pd_baseline_id,
                          srs,rbs_total,sdq_total,adhd_inatt,adhd_hyper,anx_beck,dep_beck
                          #rpd_response201_id,rpd_response202_id,rpd_response203_id,rpd_response204_id,
                          #rpd_auc201_id,rpd_auc202_id,rpd_auc203_id,rpd_auc204_id
                          )

##group differences
groupdiff_p<-c(NA,
               round(as.numeric(with(df_dem,chisq.test(t1_sex,t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,chisq.test(timepoints,t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(t1_ageyrs~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(t1_fsiq~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(t1_piq~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(t1_viq~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(missing_data_trial~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_timepoint,chisq.test(sampling_rate,t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(center_dev~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(screen_dist~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(pd_baseline~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(t1_srs_rawscore~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(t1_rbs_total~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(t1_sdq_total_difficulties_p~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(adhd_inatt~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(adhd_hyper~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(anx_beck~t1_diagnosis))['p.value']),3),
               round(as.numeric(with(df_dem,t.test(dep_beck~t1_diagnosis))['p.value']),3)
               # round(as.numeric(with(df_dem,t.test(rpd_response.201~t1_diagnosis))['p.value']),3),
               # round(as.numeric(with(df_dem,t.test(rpd_response.202~t1_diagnosis))['p.value']),3),
               # round(as.numeric(with(df_dem,t.test(rpd_response.203~t1_diagnosis))['p.value']),3),
               # round(as.numeric(with(df_dem,t.test(rpd_response.204~t1_diagnosis))['p.value']),3),
               # round(as.numeric(with(df_dem,t.test(rpd_auc.201~t1_diagnosis))['p.value']),3),
               # round(as.numeric(with(df_dem,t.test(rpd_auc.202~t1_diagnosis))['p.value']),3),
               # round(as.numeric(with(df_dem,t.test(rpd_auc.203~t1_diagnosis))['p.value']),3),
               # round(as.numeric(with(df_dem,t.test(rpd_auc.204~t1_diagnosis))['p.value']),3)
               )

groupdiff_p[which(groupdiff_p==0)]<-'<0.001'
groupdiff_p[which(is.na(groupdiff_p))]<-'-'

row_names<-c('n','gender (F/M)','timepoints (1/2/1+2)','age (in years)','IQ','perceptual IQ','verbal IQ',
             #'data quality: precision','data quality: accuracy',
             #'sampling rate (120Hz/300Hz)',
             'missing data per trial (%)','sampling rate (300Hz / 120Hz)',
             'gaze center deviation (%)','screen distance (mm)','mean pupil size (mm)',
             'SRS (total)','RBS (total)','SDQ (total)','ADHD inattention','ADHD hyperactivity','BAI (anxiety)','BDI (depression)'
             # 'pupillary response: amplitude - standard (%)','pupillary response: amplitude - oddball pitch (%)','pupillary response: amplitude - oddball length (%)','pupillary response: amplitude - oddball both (%)',
             # 'pupillary response: AUC - standard (%)','pupillary response: AUC - oddball pitch (%)','pupillary response: AUC - oddball length (%)','pupillary response: AUC - oddball both (%)'
             )

descriptives_table<-cbind(row_names,descriptives_table,groupdiff_p)

#add group differences
#descriptives_table<-ifelse(descriptives_table=='0','<0.001',descriptives_table)

table_sample<-descriptives_table %>%
  kbl(caption = "Sample description",
      col.names = c('','autistic individuals (ASD)','neurotypical individuals (NTC)','group difference (p)'),
      row.names = F) %>%
  kable_classic(full_width = F, html_font = "Cambria")


descriptives_table

table_sample

save_kable(table_sample, file=paste0(project_path,'/output/table_sampledescription.html'))




```

# pupil size change signal

```{r pupil size change signal}

#sample data
sampled_df<-df[sample(1:nrow(df),nrow(df)/10),]

#ON FULL DATA - takes 1hour+ to complete
#sampled_df<-df #


g1<-ggplot(sampled_df[sampled_df$time_event<0.6,],aes(x=time_event,y=rpd,group=EventData,color=EventData,fill=EventData))+
  geom_smooth(alpha=0.4)+
  labs(x='trial duration (s)',y='change in pupil size (mm)')+
  scale_fill_manual(values = custom_condition_colors, labels=c("201" = "standard", "202" = "pitch oddball", "203" = "length oddball ", "204" = "pitch & length oddball"))+
  scale_color_manual(values = custom_condition_colors, labels=c("201" = "standard", "202" = "pitch oddball", "203" = "length oddball ", "204" = "pitch & length oddball"))


#add demographics data
df_dem_merge<-df_dem[,c('subjects','t1_group','t1_diagnosis','t1_sex','t1_ageyrs','t2_ageyrs','t1_fsiq','t1_piq','t1_viq')]
df_dem_merge$subjects<-as.character(df_dem_merge$subjects)
sampled_df$subjects<-substr(sampled_df$id,1,12)
sampled_df<-merge(sampled_df,df_dem_merge,by='subjects') ###--> takes a while

    
#define thirds
sampled_df$trial_position<-ifelse(sampled_df$EventCounter<350,'first quarter',
                                ifelse(sampled_df$EventCounter>1050,'last quarter',
                                       ifelse(sampled_df$EventCounter>=350 & sampled_df$EventCounter<=700,'second quarter',
                                              ifelse(sampled_df$EventCounter>700 & sampled_df$EventCounter<=1050,'third quarter',NA
                                       ))))

sampled_df$trial_position<-factor(sampled_df$trial_position,levels=c('first quarter','second quarter','third quarter','last quarter'))

#
g2<-ggplot(sampled_df[sampled_df$time_event<0.60 & !is.na(sampled_df$trial_position),],
       aes(x=time_event,y=rpd,group=interaction(t1_diagnosis,EventData),color=EventData,linetype=t1_diagnosis))+
  facet_grid(EventData ~ trial_position)+
  geom_smooth(formula = y ~ x + poly(x,4))+
  scale_linetype_discrete(labels=c("ASD" = "autistic", "Control" = "non-autistic"))+
  scale_color_manual(values = custom_condition_colors, 
                     labels=c("201" = "standard", "202" = "pitch oddball", "203" = "length oddball ", "204" = "pitch & length oddball"))+
  labs(x='trial duration (s)',y='change in pupil size (mm)',color='task condition',linetype='group')+
  theme(strip.text.y = element_blank()) #remove labels on facet axis

#print in markdown
grid.arrange(g1+theme(legend.position = 'none'),g2,widths=c(1,1.3))    
        
#save to file
tiff(file=paste0(project_path,"/output/figures/pupil_size_signal_effects_SAMPLED.tiff"), # create a file in tiff format in current working directory
  width=12, height=4, units="in", res=300, compression='lzw') #define size and resolution of the resulting figure
      
grid.arrange(g1+theme(legend.position = 'none'),g2,widths=c(1,1.3))    

dev.off() #close operation and save file


```


# trial effects

```{r BPS_SEPR_association}

#interrelation of BPS and SEPR
lmm<-lmer(scale(rpd_auc)~scale(pd_baseline)+
            (1|subjects)+(1|wave),data=df_trial)
anova(lmm)

cbind(round(fixef(lmm)['scale(pd_baseline)'],2),
              round(confint(lmm,parm = 'scale(pd_baseline)'),2))

#model fit
r2_nakagawa(lmm)  
  
#BIC Bayes Factor
lmm_ML<-lmer(scale(rpd_auc)~scale(pd_baseline)+
              (1|subjects)+(1|wave),data=df_trial,REML=F)

null_lmm_ML <- lmer(scale(rpd_auc)~1+
                   (1|subjects)+(1|wave),data=df_trial,REML=F)

BF_BIC <- exp((BIC(null_lmm_ML) - BIC(lmm_ML))/2)  
BF_BIC  

```  

```{r BPS_SEPR_association_Bayesian}

 # data - create greta arrays
    x <- as_data(scale(df_trial$pd_baseline))
    y <- as_data(scale(df_trial$rpd_auc))
    subject_id <- as.integer(factor(df_trial$subjects)) #random intercept (in LMM)

    
    # variables and priors
    int <- normal(0, 1)
    coef <- normal(0, 1)
    sd <- student(3, 0, 1, truncation = c(0, Inf))
    a_subject <- normal(0, 1, dim = max(subject_id))

    # operations
    mean <- int + coef * x + a_subject[subject_id]

    # likelihood - distribution over data
    distribution(y) <- normal(mean, sd)

    # defining the model
    m <- model(int, coef, sd)

    # plotting
    #require(DiagrammeR)
    plot(m)

    # sampling
    draws <- mcmc(m, n_samples = number_of_iterations, warmup = number_of_warmups)
    summary(draws)
    
    mcmc_trace(draws) #see whether chains converge and are stationary
    mcmc_dens(draws) # + stable estimates
    
    #posterior predictive checking
    coda::gelman.diag(draws) #Rhat <= 1.01 is cutoff for reliable estimator
    coda::effectiveSize(draws) #ESS

    #save model
    draws_SEPR_BPS<-draws
    save(draws_SEPR_BPS,file=paste0(project_path,'/data/Bayesian_model_SEPR_BPS.Rdata'))


```


```{r task_effects_on_BPS}


##BPS
  
## include trial characteristics - TASK PROGRESSION
  lmm<-lmer(scale(pd_baseline)~EventCounter+
              (1|subjects)+(1|wave),data=df_trial)
  
  anova(lmm)
  
  cbind(round(fixef(lmm)['EventCounter'],9),
                round(confint(lmm,parm = 'EventCounter'),9))

  
  confint(contrast(emmeans(lmm,~EventCounter,at=list(EventCounter =     seq(1,1400,1399))),'pairwise'))

r2_nakagawa(lmm)  
 

#BIC Bayes Factor
lmm_ML<-lmer(scale(pd_baseline)~EventCounter+
              (1|subjects)+(1|wave),data=df_trial,REML=F)

null_lmm_ML <- lmer(scale(pd_baseline)~1+
                   (1|subjects)+(1|wave),data=df_trial,REML=F)

BF_BIC <- exp((BIC(null_lmm_ML) - BIC(lmm_ML))/2)  
BF_BIC  
 
  
## include trial characteristics - TRIAL CONDITION
lmm<-lmer(scale(pd_baseline)~EventData+
            (1|subjects)+(1|wave),data=df_trial)

anova(lmm)
emmeans(lmm,~EventData)
confint(contrast(emmeans(lmm,~EventData),'pairwise'))
###--> 201 > 202 + 204; 203 > 202

r2_nakagawa(lmm)  
  
#BIC Bayes Factor
lmm_ML<-lmer(scale(pd_baseline)~EventData+
              (1|subjects)+(1|wave),data=df_trial,REML=F)

# null_lmm_ML <- lmer(scale(pd_baseline)~1+
#                    (1|subjects)+(1|wave),data=df_trial,REML=F)

BF_BIC <- exp((BIC(null_lmm_ML) - BIC(lmm_ML))/2)  
BF_BIC  
 
```

```{r task_effects_progression_on_BPS_Bayesian}

 # data - create greta arrays
    y <- as_data(scale(df_trial$pd_baseline))
    trials <- as_data(scale(df_trial$EventCounter))
    subject_id <- as.integer(factor(df_trial$subjects)) #random intercept (in LMM)

    
    # variables and priors
    int <- normal(0, 1)
    coef <- normal(0, 1)
    sd <- student(3, 0, 1, truncation = c(0, Inf))
    a_subject <- normal(0, 1, dim = max(subject_id))

    # operations
    mean <- int + coef * trials + a_subject[subject_id]

    # likelihood - distribution over data
    distribution(y) <- normal(mean, sd)

    # defining the model
    m <- model(int, coef, sd)

    # sampling
    draws <- mcmc(m, n_samples = number_of_iterations, warmup = number_of_warmups)
    summary(draws)
    
    #diangostics
    mcmc_trace(draws) #see whether chains converge and are stationary
    mcmc_dens(draws) # + stable estimates

    #posterior predictive checking
    coda::gelman.diag(draws) #Rhat <= 1.01 is cutoff for reliable estimator
    coda::effectiveSize(draws) #ESS

    #save model
    draws_BPS_taskprogression<-draws
    save(draws_BPS_taskprogression,file=paste0(project_path,'/data/Bayesian_model_BPS_taskprogression.Rdata'))


```


```{r task_effects_condition_on_BPS_Bayesian}

    # data - create greta arrays
    y <- as_data(scale(df_trial$pd_baseline))
    events <- as_data(model.matrix(~ EventData - 1, df_trial)) #alternative to dummy coding?
    subject_id <- as.integer(factor(df_trial$subjects)) #random intercept (in LMM)

    # variables and priors
    int <- normal(0, 1)
    event_coef<- normal(0, 1, dim=ncol(events))
    sd <- student(3, 0, 1, truncation = c(0, Inf))
    a_subject <- normal(0, 1, dim = max(subject_id))

    # operations
    mean <- events %*% event_coef + a_subject[subject_id]

    # likelihood - distribution over data
    distribution(y) <- normal(mean, sd)

    # defining the model
    m <- model(event_coef)

    # sampling
    draws <- mcmc(m, n_samples = number_of_iterations, warmup = number_of_warmups)
    summary(draws)
    
    mcmc_intervals(draws, prob= .66, prob_outer = .95)
    
    mcmc_trace(draws) #see whether chains converge and are stationary
    mcmc_dens(draws) # + stable estimates

    #posterior predictive checking
    coda::gelman.diag(draws) #Rhat <= 1.01 is cutoff for reliable estimator
    coda::effectiveSize(draws) #ESS

    #save model
    draws_BPS_trialcondition<-draws
    save(draws_BPS_trialcondition,file=paste0(project_path,'/data/Bayesian_model_BPS_trialcondition.Rdata'))

```

```{r task_effects_on_SEPR}

##SEPR
## include trial characteristics - TASK PROGRESSION
  lmm<-lmer(scale(rpd_auc)~EventCounter+
              (1|subjects)+(1|wave),data=df_trial)
  anova(lmm)
  
  cbind(round(fixef(lmm)['EventCounter'],9),
                round(confint(lmm,parm = 'EventCounter'),9))

  confint(contrast(emmeans(lmm,~EventCounter,at=list(EventCounter =   seq(1,1400,1399))),'pairwise'))
  
r2_nakagawa(lmm)  
  
#BIC Bayes Factor
lmm_ML<-lmer(scale(rpd_auc)~EventCounter+
              (1|subjects)+(1|wave),data=df_trial,REML=F)

null_lmm_ML <- lmer(scale(rpd_auc)~1+
                   (1|subjects)+(1|wave),data=df_trial,REML=F)

BF_BIC <- exp((BIC(null_lmm_ML) - BIC(lmm_ML))/2)  
BF_BIC  

  
## include trial characteristics - TRIAL CONDITION
lmm<-lmer(scale(rpd_auc)~EventData+
            (1|subjects)+(1|wave),data=df_trial)

anova(lmm)
emmeans(lmm,~EventData)
confint(contrast(emmeans(lmm,~EventData),'pairwise'))
###--> 201 > 202 + 204; 203 > 202

r2_nakagawa(lmm)  
  
#BIC Bayes Factor  
lmm_ML<-lmer(scale(rpd_auc)~EventData+
          (1|subjects)+(1|wave),data=df_trial,REML=F)

null_lmm_ML <- lmer(scale(rpd_auc)~1+
                 (1|subjects)+(1|wave),data=df_trial,REML=F)

BF_BIC <- exp((BIC(null_lmm_ML) - BIC(lmm_ML))/2)  # BICs to Bayes factor
BF_BIC
  
```

```{r task_effects_progression_on_SEPR_Bayesian}

 # data - create greta arrays
    y <- as_data(scale(df_trial$rpd_auc))
    trials <- as_data(scale(df_trial$EventCounter))
    subject_id <- as.integer(factor(df_trial$subjects)) #random intercept (in LMM)

    
    # variables and priors
    int <- normal(0, 1)
    coef <- normal(0, 1)
    sd <- student(3, 0, 1, truncation = c(0, Inf))
    a_subject <- normal(0, 1, dim = max(subject_id))

    # operations
    mean <- coef * trials + a_subject[subject_id]

    # likelihood - distribution over data
    distribution(y) <- normal(mean, sd)

    # defining the model
    m <- model(coef)

    # sampling
    draws <- mcmc(m, n_samples = number_of_iterations, warmup = number_of_warmups)
    summary(draws)
    
    mcmc_trace(draws) #see whether chains converge and are stationary
    mcmc_dens(draws) # + stable estimates

    #posterior predictive checking
    coda::gelman.diag(draws) #Rhat <= 1.01 is cutoff for reliable estimator
    coda::effectiveSize(draws) #ESS

    #save model
    draws_SEPR_taskprogression<-draws
    save(draws_SEPR_taskprogression,file=paste0(project_path,'/data/Bayesian_model_SEPR_taskprogression.Rdata'))
    
```


```{r task_effects_condition_on_SEPR_Bayesian}

    # data - create greta arrays
    y <- as_data(scale(df_trial$rpd_auc))
    events <- as_data(model.matrix(~ EventData - 1, df_trial)) #alternative to dummy coding?
    subject_id <- as.integer(factor(df_trial$subjects)) #random intercept (in LMM)

    # variables and priors
    int <- normal(0, 1)
    event_coef<- normal(0, 1, dim=ncol(events))
    sd <- student(3, 0, 1, truncation = c(0, Inf))
    a_subject <- normal(0, 1, dim = max(subject_id))

    # operations
    mean <- int + events %*% event_coef + a_subject[subject_id]

    # likelihood - distribution over data
    distribution(y) <- normal(mean, sd)

    # defining the model
    m <- model(event_coef)

    # sampling
    draws <- mcmc(m, n_samples = number_of_iterations, warmup = number_of_warmups)
    summary(draws)
    
    mcmc_intervals(draws, prob= .66, prob_outer = .95)+scale_y_discrete(labels=c('standard','pitch oddball','length oddball','pitch & length oddball'))+coord_flip()+theme_bw()
    
    mcmc_trace(draws) #see whether chains converge and are stationary
    mcmc_dens(draws) # + stable estimates

    
    #posterior predictive checking
    coda::gelman.diag(draws) #Rhat <= 1.01 is cutoff for reliable estimator
    coda::effectiveSize(draws) #ESS

    #save model
    draws_SEPR_taskcondition<-draws
    save(draws_SEPR_taskcondition,file=paste0(project_path,'/data/Bayesian_model_SEPR_taskcondition.Rdata'))
        
```


```{r figure_task_effects}

#SEPR -pupillary response - technical model
lmm<-lmer(scale(rpd_auc)~EventData+
              (1|subjects)+(1|wave),data=df_trial)

#create plot --> of contrasts
plot_task_effect<-plot(contrast(emmeans(lmm,~EventData),'pairwise'))[['data']]

#modify plot
g2<-ggplot(plot_task_effect,aes(x=contrast,y=the.emmean))+
  #conventional error bar
  geom_errorbar(aes(min=asymp.LCL,max=asymp.UCL),width=0.2)+
  
    #boxplot
  geom_boxplot(aes(fill=contrast,
                   middle=the.emmean,
                   lower=the.emmean-1.5*SE,
                   upper=the.emmean+1.5*SE,
                   ymin=asymp.LCL,
                   ymax=asymp.UCL),stat = "identity",alpha=0.7)+
  scale_fill_manual(values = custom_contrast_colors,labels = c('standard - pitch','standard - length','standard - pitch & length','pitch - length','pitch - pitch & length','length - pitch & length'))+
  scale_x_discrete(labels = NULL, breaks = NULL)+ #remove x-axis tick labels
  coord_cartesian(ylim = c(-0.1, 0.1))+
  labs(x='contrast of task condition',y='SEPR difference (z)')
  
#BPS
lmm<-lmer(scale(pd_baseline)~EventData+
              (1|subjects)+(1|wave),data=df_trial)

#create plot --> of contrasts
plot_task_effect<-plot(contrast(emmeans(lmm,~EventData),'pairwise'))[['data']]

#modify plot
g1<-ggplot(plot_task_effect,aes(x=contrast,y=the.emmean))+
  #conventional error bar
  geom_errorbar(aes(min=asymp.LCL,max=asymp.UCL),width=0.2)+
  
  # #overplot predicted values
  # geom_jitter(data=df_plot_predicted_bps[complete.cases(df_plot_predicted_bps),],
  #             aes(x=predicted_bps_eventdata,
  #                 y=predicted_bps_mean,color=predicted_bps_eventdata),alpha=0.3,width=0.4,show.legend=F)+
  #boxplot
  geom_boxplot(aes(fill=contrast,
                   middle=the.emmean,
                   lower=the.emmean-1.5*SE,
                   upper=the.emmean+1.5*SE,
                   ymin=asymp.LCL,
                   ymax=asymp.UCL),stat = "identity",alpha=0.7)+
  scale_fill_manual(values = custom_contrast_colors,labels = c('standard - pitch','standard - length','standard - pitch & length','pitch - length','pitch - pitch & length','length - pitch & length'))+
  scale_x_discrete(labels = NULL, breaks = NULL)+ #remove x-axis tick labels
  coord_cartesian(ylim = c(-0.1, 0.1))+
  labs(x='contrast of task condition',y='BPS difference (z)')
  
###save figure

#plot in markdown
grid.arrange(g1+theme(legend.position="none"),g2,widths=c(1.23,2))  

tiff(file=paste0(project_path,"/output/figures/taskcondition_effects.tiff"), # create a file in tiff format in current working directory
  width=10, height=4, units="in", res=300, compression='lzw') #define size and resolution of the resulting figure
      
grid.arrange(g1+theme(legend.position="none"),g2,widths=c(1.23,2))  

dev.off() #close operation and save file


```


# baseline pupil size (BPS)

```{r BPS_taskprogressionLMM}

#main model
lmm_REML<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*EventCounter+
              (1|subjects)+(1|wave),data=df_trial)

#fixed effect significances
anova(lmm_REML)

#model fit
r2_nakagawa(lmm_REML)

#POST-HOC

#Post-hoc - between group
emtrends(lmm_REML,~t1_diagnosis,var='EventCounter')
#magnitude of change relative to SE
emmeans(lmm_REML,~t1_diagnosis+EventCounter,at=list(EventCounter = seq(1,1400,1399)))

  confint(contrast(emmeans(lmm_REML,~EventCounter|t1_diagnosis,at=list(EventCounter =   seq(1,1400,1399))),'revpairwise'))


#Post-hoc - between condition
emtrends(lmm_REML,~EventData,var='EventCounter')

#Bayes factor - group x task progression
lmm_ML<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*EventCounter+
              (1|subjects)+(1|wave),data=df_trial,REML=F)

null_lmm_ML <- lmer(scale(pd_baseline)~EventData+t1_diagnosis+EventCounter+
                   EventData:EventCounter+EventData:t1_diagnosis+
              (1|subjects)+(1|wave),data=df_trial,REML=F)

BF_BIC <- exp((BIC(null_lmm_ML) - BIC(lmm_ML))/2)  # BICs to Bayes factor
BF_BIC

#Bayes factor - trial condition x task progression
null_lmm_ML <- lmer(scale(pd_baseline)~EventData+t1_diagnosis+EventCounter+
                   EventData:t1_diagnosis+t1_diagnosis:EventCounter+
              (1|subjects)+(1|wave),data=df_trial,REML=F)

        BF_BIC <- exp((BIC(null_lmm_ML) - BIC(lmm_ML))/2)  # BICs to Bayes factor
        BF_BIC
        
        
#full model        
lmm_full<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*EventCounter+
      scale(ageyrs)+scale(t1_piq)+sex+
      as.factor(sampling_rate)+scale(center_dev)+scale(missing_data_trial)+
      (1|subjects)+(1|wave),data=df_trial)

anova(lmm_full)

#coefficient of determination
r2_nakagawa(lmm_full)


##supplements - full table
  row_names<-c('trial condition (TC)','group','task progression (TP)',
               'age','perceptual IQ','sex',
               'sampling rate','gaze center deviation','data quality',
               'TC x group','TC x TP','group x TP','TC x group x TP')
  
  
  table_data_model<-round(anova(lmm_full),3)
  table_data_model<-cbind(row_names,table_data_model)
  
  table_data_model
  
  table_model<-table_data_model %>%
    kbl(caption = "Linear mixed model: baseline pupil size (BPS)",
        col.names = c('','Sum Sq','Mean Sq','df1','df2','F','p'),
        row.names = F) %>%
    kable_classic(full_width = F, html_font = "Cambria")
  
  
  table_model
  
  save_kable(table_model, file= 'output/supplements/table_model_BPS.html')
  
```

```{r BPS_taskprogression_Bayesian}

####--> reun with more iterations

# A. translate data - make greta arrays
y <- as_data(scale(df_trial$pd_baseline))
design <- as.matrix(cbind(ifelse(df_trial$t1_diagnosis=='ASD',T,F),df_trial$EventCounter))
subject_id <- as.integer(factor(df_trial$subjects)) #random intercept (in LMM)

#define priors
int <- normal(0, 1)
design_coef<- normal(0, 1, dim=ncol(design))
sd <- cauchy(0, 3, truncation = c(0, Inf))
#sd <- student(3, 0, 1, truncation = c(0, Inf))
a_subject <- normal(0, 1, dim = max(subject_id))

#OPERATIONS - MODEL
mean <- int + design %*% design_coef + a_subject[subject_id]

# likelihood - distribution over data
distribution(y) <- normal(mean, sd)

# defining the model
m <- model(design_coef)

# sampling
start <-Sys.time()
draws <- mcmc(m, n_samples = number_of_iterations, warmup = number_of_warmups,) ###--> test
Sys.time() - start

#stability of estimates
mcmc_trace(draws) #see whether chains converge and are stationary
mcmc_dens(draws) # + stable estimates

#analyse
summary(draws)
plot(draws)

#posterior predictive checking
coda::gelman.diag(draws) #Rhat <= 1.01 is cutoff for reliable estimator
coda::effectiveSize(draws) #ESS

#save model
draws_BPS_twoway<-draws
save(draws_BPS_twoway,file=paste0(project_path,'/data/Bayesian_model_BPS_twoway.Rdata'))
    

```

```{r BPS_habituation_LMM}

  with(df_trial,table(sequence_position,EventData))
  ###--> weird distribution?

  #recoding
  df_trial$sequence_position_z<-scale(df_trial$sequence_position)

    #figure
  df_trial$standardtrial<-with(df_trial,ifelse(EventData==201,T,F))
  ggplot(df_trial[df_trial$sequence_position<=10,],aes(x=sequence_position,y=scale(pd_baseline),group=interaction(standardtrial,t1_diagnosis),color=standardtrial,linetype=t1_diagnosis))+
    geom_smooth()+labs(x='sequence position',y='BPS (z)')+scale_x_continuous(breaks=1:10)+theme_bw()
  ggplot(df_trial[df_trial$sequence_position<=10,],aes(x=sequence_position,y=scale(rpd_response),group=interaction(standardtrial,t1_diagnosis),color=t1_diagnosis,linetype=standardtrial))+
    geom_smooth()+labs(x='sequence position',y='SEPR (z)')+scale_x_continuous(breaks=1:10)+theme_bw()


  #BPS - continuous
  lmm<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*sequence_position_z+
              (1|subjects)+(1|wave),data=df_trial[df_trial$sequence_position<10,])

  #model fit
  anova(lmm)
  r2_nakagawa(lmm)

        ### supplementary analysis
        lmm<-lmer(scale(pd_baseline)~t1_diagnosis*sequence_position_z+
                    (1|subjects)+(1|wave),data=df_trial[df_trial$EventData==201 & df_trial$sequence_position<10,])

        #model fit
        anova(lmm)


        #BIC Bayes Factor
        lmm_ML<-lmer(scale(pd_baseline)~t1_diagnosis*sequence_position_z+
                       (1|subjects)+(1|wave),data=df_trial[df_trial$EventData==201 & df_trial$sequence_position<10,],REML=F)

        null_lmm_ML <- lmer(scale(pd_baseline)~sequence_position_z+
                              (1|subjects)+(1|wave),data=df_trial[df_trial$EventData==201 & df_trial$sequence_position<10,],REML=F)

        BF_BIC <- exp((BIC(null_lmm_ML) - BIC(lmm_ML))/2)
        BF_BIC

  #BPS categorical
  lmm<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*as.factor(sequence_position)+
              (1|subjects)+(1|wave),data=df_trial[df_trial$sequence_position<4,])

  anova(lmm)
  contrast(emmeans(lmm,~as.factor(sequence_position)),'pairwise')
  ###-> 1-3 effect
  ###inclusion of covariates leads to boundary singular

  lmm<-lmer(scale(pd_baseline)~t1_diagnosis*as.factor(sequence_position)+
              (1|subjects)+(1|wave),data=df_trial[df_trial$EventData==201 & df_trial$sequence_position<4,])

```

```{r BPS_habituation_Bayesian}


df_bps_bayesian_habituation<-df_trial[df_trial$EventData==201 & df_trial$sequence_position<10,]

# A. translate data - make greta arrays
y <- as_data(scale(df_bps_bayesian_habituation$pd_baseline))
design <- as.matrix(cbind(ifelse(df_bps_bayesian_habituation$t1_diagnosis=='ASD',T,F),df_bps_bayesian_habituation$sequence_position))
subject_id <- as.integer(factor(df_bps_bayesian_habituation$subjects)) #random intercept (in LMM)

#define priors
int <- normal(0, 1)
design_coef<- normal(0, 1, dim=ncol(design))
sd <- cauchy(0, 3, truncation = c(0, Inf))
#sd <- student(3, 0, 1, truncation = c(0, Inf))
a_subject <- normal(0, 1, dim = max(subject_id))

#OPERATIONS - MODEL
mean <- int + design %*% design_coef + a_subject[subject_id]

# likelihood - distribution over data
distribution(y) <- normal(mean, sd)

# defining the model
m <- model(design_coef)

# sampling
start <-Sys.time()
draws <- mcmc(m, n_samples = number_of_iterations, warmup = number_of_warmups,) ###--> test
Sys.time() - start

#stability of estimates
mcmc_trace(draws) #see whether chains converge and are stationary
mcmc_dens(draws) # + stable estimates

#analyse
summary(draws)
plot(draws)

#posterior predictive checking
coda::gelman.diag(draws) #Rhat <= 1.01 is cutoff for reliable estimator
coda::effectiveSize(draws) #ESS

#save model
draws_BPS_supp<-draws
save(draws_BPS_supp,file=paste0(project_path,'/data/Bayesian_model_BPS_supp.Rdata'))


```

# stimulus-evoked pupillary response

```{r SEPR_LMM}

#MAIN MODEL - pupillary response by group - random intercept
lmm_REML<-lmer(scale(rpd_auc)~EventData*t1_diagnosis*EventCounter+
            (1|subjects)+(1|wave),data=df_trial)
            #--> group effect (interaction) is robust in reduced and full model

#fixed effect significances
anova(lmm_REML)

#Bayes factor - group x task progression
lmm_ML<-lmer(scale(rpd_auc)~EventData*t1_diagnosis*EventCounter+
                (1|subjects)+(1|wave),data=df_trial,REML=F)

null_lmm_ML <- lmer(scale(rpd_auc)~EventData+EventCounter+
                 EventData:EventCounter+EventData:t1_diagnosis:EventCounter+
                (1|subjects)+(1|wave),data=df_trial,REML=F)

  BF_BIC <- exp((BIC(null_lmm_ML) - BIC(lmm_ML))/2)  # BICs to Bayes factor
  BF_BIC


#full model
lmm_full<-lmer(scale(rpd_auc)~EventData*t1_diagnosis*EventCounter+
               scale(ageyrs)+scale(t1_piq)+sex+
               scale(center_dev)+as.factor(sampling_rate)+scale(missing_data_trial)+
              (1|subjects)+(1|wave),data=df_trial)
              #--> group effect (interaction) is robust in reduced and full model

anova(lmm_full)

confint(contrast(emmeans(lmm_full,~EventData|t1_diagnosis),'revpairwise'))

#coefficient of determination
r2_nakagawa(lmm_full)


hist(scale(df_trial$rpd_auc))

confint(contrast(emtrends(lmm_REML,~t1_diagnosis|EventData,var='EventCounter'),'pairwise'))
      plot(emtrends(lmm_REML,~t1_diagnosis|EventData,var='EventCounter'))
      ### --> attenuated habituation in ASD for pitch oddballs (only contrast significant in pairwise comparison)
      ##--> for rpd_auc higher pitch response in controls, higher oddball length response in ASD

```

```{r SEPR_Bayesian_three_way_interaction}

# A. translate data - make greta arrays
y <- as_data(scale(df_trial$rpd_auc))
trials <- as_data(scale(df_trial$EventCounter))
subject_id <- as.integer(factor(df_trial$subjects)) #random intercept (in LMM)
events <- as_data(model.matrix(~ EventData - 1, df_trial)) #alternative to dummy coding?
interaction_variable<-with(df_trial,interaction(t1_diagnosis,EventData))
group_by_events <- as_data(model.matrix(~interaction_variable-1, df_trial)) #alternative to dummy coding - remove intercept (-1)
#table(group_by_events[,1],group_by_events[,9])

with(df_trial,interaction(t1_diagnosis,EventData))

#define priors
event_coefs<- normal(0, 1, dim=ncol(events))
group_event_coefs <- normal(0,1, dim=ncol(group_by_events))

sd <- cauchy(0, 3, truncation = c(0, Inf))
a_subject <- normal(0, 1, dim = max(subject_id))

#OPERATIONS - MODEL
mean <- trials * group_by_events %*% group_event_coefs + a_subject[subject_id]

# likelihood - distribution over data
distribution(y) <- normal(mean, sd)

# defining the model
#m <- model(int, coef_201, coef_202, coef_203, coef_204, sd)
m <- model(group_event_coefs)

# sampling
start <-Sys.time()
draws <- mcmc(m, n_samples = number_of_iterations, warmup = number_of_warmups) ###--> test
Sys.time() - start


#estimator convergence
mcmc_trace(draws) #see whether chains converge and are stationary
mcmc_dens(draws) # + stable estimates

##results
mcmc_areas(draws, prob= .66, prob_outer = .95)+scale_y_discrete(labels=c('ASD-standard','TD-standard ','ASD-pitch','TD-pitch','ASD-length ','TD-length','ASD-pitch+length','TD-pitch+length'))+coord_flip()+theme_bw()

#analyse
summary(draws)


#posterior predictive checking
coda::gelman.diag(draws) #Rhat <= 1.01 is cutoff for reliable estimator
coda::effectiveSize(draws) #ESS

summary(draws_SEPR_threeway)

#save model
draws_SEPR_threeway<-draws
save(draws_SEPR_threeway,file=paste0(project_path,'/data/Bayesian_model_SEPR_threewayinteraction.Rdata'))


```

```{r SEPR_habituation_LMM}

  #SEPR
  lmm<-lmer(scale(rpd_auc)~EventData*t1_diagnosis*sequence_position_z+
              (1|subjects)+(1|wave),data=df_trial[df_trial$sequence_position<10,])

  anova(lmm)


  lmm<-lmer(scale(rpd_auc)~EventData*t1_diagnosis*as.factor(sequence_position)+
              (1|subjects)+(1|wave),data=df_trial[df_trial$sequence_position<4,])


      #BIC Bayes Factor
      lmm_ML<-lmer(scale(rpd_auc)~EventData*t1_diagnosis*as.factor(sequence_position)+
                     (1|subjects)+(1|wave),data=df_trial[df_trial$sequence_position<4,],REML=F)

      null_lmm_ML <- lmer(scale(rpd_auc)~1+
                            (1|subjects)+(1|wave),data=df_trial[df_trial$sequence_position<4,],REML=F)

      BF_BIC <- exp((BIC(null_lmm_ML) - BIC(lmm_ML))/2)
      BF_BIC

      BIC(null_lmm_ML)
      BIC(lmm_ML)


  lmm_full<-lmer(scale(rpd_auc)~EventData*t1_diagnosis*sequence_position_z+
                scale(ageyrs)+scale(t1_piq)+sex+
                 scale(center_dev)+as.factor(sampling_rate)+scale(missing_data_trial)+
              (1|subjects)+(1|wave),data=df_trial[df_trial$sequence_position<10,])
    
  anova(lmm_full)
  ###--> if an oddballs follows an oddball - higehr response in ASD
  ###--> if oddball follows a standard - higher response in TD

  contrast(emmeans(lmm,~t1_diagnosis|EventData+as.factor(sequence_position)),'pairwise')
  confint(contrast(emmeans(lmm,~t1_diagnosis|EventData+as.factor(sequence_position)),'revpairwise'))

```


```{r SEPR_habituation_Bayesian}

df_sepr_bayesian_habituation<-df_trial[df_trial$sequence_position<4,]

# A. translate data - make greta arrays
y <- as_data(scale(df_sepr_bayesian_habituation$rpd_auc))
interaction_variable<-with(df_sepr_bayesian_habituation,interaction(t1_diagnosis,sequence_position))
group_by_events <- as_data(model.matrix(~interaction_variable-1, df_sepr_bayesian_habituation)) #alternative to dummy coding - remove intercept (-1)
subject_id <- as.integer(factor(df_sepr_bayesian_habituation$subjects)) #random intercept (in LMM)

#define priors
int <- normal(0, 1)
design_coef<- normal(0, 1, dim=ncol(group_by_events))
sd <- cauchy(0, 3, truncation = c(0, Inf))
a_subject <- normal(0, 1, dim = max(subject_id))

#OPERATIONS - MODEL
mean <- int + group_by_events %*% design_coef + a_subject[subject_id]

# likelihood - distribution over data
distribution(y) <- normal(mean, sd)

# defining the model
m <- model(design_coef)

# sampling
start <-Sys.time()
draws <- mcmc(m, n_samples = number_of_iterations, warmup = number_of_warmups,) ###--> test
Sys.time() - start

#stability of estimates
mcmc_trace(draws) #see whether chains converge and are stationary
mcmc_dens(draws) # + stable estimates

#analyse
table(interaction_variable) #names of coefficients
summary(draws)
plot(draws)

#posterior predictive checking
coda::gelman.diag(draws) #Rhat <= 1.01 is cutoff for reliable estimator
coda::effectiveSize(draws) #ESS

#save model
draws_SEPR_habituation<-draws
save(draws_SEPR_habituation,file=paste0(project_path,'/data/Bayesian_model_SEPR_habituation.Rdata'))

```

# figure group differences

```{r figure_BPS_SEP_between_groups}
#main models
BPS_progression<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*EventCounter+
              (1|subjects)+(1|wave),data=df_trial)

BPS_habituation<-lmer(scale(pd_baseline)~t1_diagnosis*sequence_position+
                    (1|subjects)+(1|wave),data=df_trial[df_trial$EventData==201 & df_trial$sequence_position<=10,])

SEPR_progression<-lmer(scale(rpd_auc)~EventData*t1_diagnosis*EventCounter+
              (EventCounter-1|subjects)+(1|wave),data=df_trial)
  

#plot interaction
model_plot_data_BPS1<-as.data.frame(emmeans(BPS_progression,~t1_diagnosis+EventCounter,
                                       at=list(EventCounter = seq(1,1400,140))))

g1<-ggplot(model_plot_data_BPS1,aes(x=EventCounter,y=emmean,group=t1_diagnosis,color=t1_diagnosis))+
  geom_crossbar(aes(ymin=emmean-1*SE,ymax=emmean+1*SE,fill=t1_diagnosis),alpha=0.8,position='dodge')+
  geom_errorbar(aes(ymin=asymp.LCL,ymax=asymp.UCL),position='dodge')+
  scale_color_manual(name = "groups", labels = c("autistic", "neurotypical"),values = brewer.pal(3, "Dark2")[1:2])+
  scale_fill_manual(name = "groups", labels = c("autistic", "neurotypical"),values = brewer.pal(3, "Dark2")[1:2])+
  labs(x='trial number')+
  theme(axis.title.y=element_blank(),legend.position = 'none')

model_plot_data_BPS2<-as.data.frame(emmeans(BPS_habituation,~t1_diagnosis+sequence_position,
                                       at=list(sequence_position = seq(1,10))))

g2<-ggplot(model_plot_data_BPS2,aes(x=sequence_position,y=emmean,group=t1_diagnosis,color=t1_diagnosis))+
  geom_crossbar(aes(ymin=emmean-1*SE,ymax=emmean+1*SE,fill=t1_diagnosis),alpha=0.8,position='dodge')+
  geom_errorbar(aes(ymin=asymp.LCL,ymax=asymp.UCL),position='dodge')+
  scale_color_manual(name = "groups", labels = c("autistic", "neurotypical"),values = brewer.pal(3, "Dark2")[1:2])+
  scale_fill_manual(name = "groups", labels = c("autistic", "neurotypical"),values = brewer.pal(3, "Dark2")[1:2])+
  scale_x_continuous(breaks=seq(0,10,1))+
  labs(x='sequence position')+
  theme(axis.title.y=element_blank(),legend.position = 'none')


model_plot_data_SEPR<-as.data.frame(emmeans(SEPR_progression,~t1_diagnosis+EventData+EventCounter,at=list(EventCounter = seq(1,1400,140))))
    
    labels <- c("201" = "standard", "202" = "pitch oddball", "203" = "length oddball", "204" = "pitch & length oddball")
g3<-ggplot(model_plot_data_SEPR,aes(x=EventCounter,y=emmean,
                           group=interaction(EventData,t1_diagnosis),color=t1_diagnosis))+
  geom_crossbar(aes(ymin=emmean-1*SE,ymax=emmean+1*SE,fill=t1_diagnosis),alpha=0.8,position='dodge')+
  geom_errorbar(aes(ymin=asymp.LCL,ymax=asymp.UCL),position='dodge')+
  scale_color_manual(name = "groups", labels = c("autistic", "neurotypical"),values = brewer.pal(3, "Dark2")[1:2])+
  scale_fill_manual(name = "groups", labels = c("autistic", "neurotypical"),values = brewer.pal(3, "Dark2")[1:2])+
  facet_wrap(~EventData,labeller=labeller(EventData = labels))+
  labs(x='trial number',y='stimulus-evoked pupillary response (z)')
  

lay <- rbind(c(1,3,3),
             c(2,3,3))

#plot in markdown
grid.arrange(g1,g2,g3, left='baseline pupil size (z)', layout_matrix=lay)


#save to file
tiff(file=paste0(project_path,"/output/figures/group_differences.tiff"), # create a file in tiff format in current working directory
  width=10, height=4, units="in", res=300, compression='lzw') #define size and resolution of the resulting figure
      
grid.arrange(g1,g2,g3, left='baseline pupil size (z)', layout_matrix=lay)

dev.off() #close operation and save file




```


# computational modelling - PCDM - neural gain

```{r PCDM_neural_gain}

#read data estimated in MAtlab
mat_output<-readMat(paste0(project_path,"/data/pcdm_estimates_1run_290323.mat"))

#extract parameters
pcdm_parameters<-mat_output[[2]]
names(pcdm_parameters)<-c('interpolateBlinks','downsampleRate','fitTimeseries','change_cutoff_by_samplingRate','low_bandpass_filter_range','blinkint_vel_thres_on','blinkint_window_from_onset','blinkint_min_dur','rel_vel_thres','min_sac_dur')

#create empty list
list_pcdm_estimates<-list()

### extract required info from matlab object in for loop
for (i in seq(length(mat_output[[1]]))){

pcdm_estimate<-mat_output[[1]][i][[1]][[1]] #extract relevant data of single participant
names(pcdm_estimate)<-dimnames(pcdm_estimate)[[1]] #assign names of dimensions
pcdm_estimate<-lapply(pcdm_estimate,unlist) # remove internal list structure

list_pcdm_estimates[[i]]<-pcdm_estimate

}

#add names
names(list_pcdm_estimates)<-sapply(list_pcdm_estimates,function(x){x['name']})

#create vectors
gain_pcdm<-unlist(sapply(list_pcdm_estimates,function(x){x['gain']}))
Rsq_pcdm<-unlist(sapply(list_pcdm_estimates,function(x){x['Rsq']}))
offset_pcdm<-unlist(sapply(list_pcdm_estimates,function(x){x['offset']}))
id<-substr(names(list_pcdm_estimates),1,nchar(names(list_pcdm_estimates))-4)
id<-id[id!=""] #remove empty entries

#exclude outliers
gain_pcdm[gain_pcdm>0.2 | gain_pcdm<(-0.2)]<-NA

#merge data
df_pcdm<-data.frame(id,gain_pcdm,Rsq_pcdm,offset_pcdm)
df_timepoint<-merge(df_timepoint,df_pcdm,by='id',all.x=T)

#data quality for neural gain
with(df_timepoint,table(Rsq_pcdm>=0.2,t1_diagnosis))
chisq.test(with(df_timepoint,table(Rsq_pcdm>=0.2,t1_diagnosis)))

#higher gain for standards in ASD
lm_gain<-lm(scale(gain_pcdm)~t1_diagnosis,df_timepoint[df_timepoint$Rsq_pcdm>0.2,])
summary(lm_gain) #higher gain in ASD for standards
anova(lm_gain) #higher gain in ASD for standards

t.test(scale(gain_pcdm)~t1_diagnosis,df_timepoint[df_timepoint$Rsq_pcdm>0.2,])
cohens_d(x=scale(gain_pcdm)~t1_diagnosis,data=df_timepoint[df_timepoint$Rsq_pcdm>0.2,])
#--> d=0.4 in ASD

#visualize
ggplot(df_timepoint[df_timepoint$Rsq_pcdm>0.2, ],aes(x=scale(gain_pcdm),fill=t1_diagnosis))+geom_histogram(aes(y = after_stat(density)),position='dodge',bins=20)+theme_bw()

###scaling with demographic data
summary(lm(scale(gain_pcdm)~ageyrs,df_timepoint[df_timepoint$Rsq_pcdm>0.2,]))
summary(lm(scale(gain_pcdm)~t1_piq,df_timepoint[df_timepoint$Rsq_pcdm>0.2,]))
summary(lm(scale(gain_pcdm)~sex,df_timepoint[df_timepoint$Rsq_pcdm>0.2,]))

# summary(lm(scale(gain_pcdm)~rpd_auc.201,df_timepoint[df_timepoint$Rsq_pcdm>0.2,]))
# summary(lm(scale(gain_pcdm)~rpd_auc.202,df_timepoint[df_timepoint$Rsq_pcdm>0.2,]))
# summary(lm(scale(gain_pcdm)~rpd_auc.203,df_timepoint[df_timepoint$Rsq_pcdm>0.2,]))
# summary(lm(scale(gain_pcdm)~rpd_auc.204,df_timepoint[df_timepoint$Rsq_pcdm>0.2,]))
# summary(lm(scale(gain_pcdm)~pd_baseline,df_timepoint[df_timepoint$Rsq_pcdm>0.2,]))


```

# supplementary analyses

## linearity of effect of trial number

```{r trial_number_modelcomparison BPS}

###polynomial fit of trial counter
  linear_fit<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*scale(EventCounter)+
          (1|subjects)+(1|wave),data=df_trial,REML=F)

  quadratic_fit<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*poly(scale(EventCounter),2)+
              (1|subjects)+(1|wave),data=df_trial,REML=F)

  cubic_fit<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*poly(scale(EventCounter),3)+
               (1|subjects)+(1|wave),data=df_trial,REML=F)
  
  quartic_fit<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*poly(scale(EventCounter),4)+
               (1|subjects)+(1|wave),data=df_trial,REML=F)

  quintic_fit<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*poly(scale(EventCounter),5)+
               (1|subjects)+(1|wave),data=df_trial,REML=F)

  sextic_fit<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*poly(scale(EventCounter),6)+
               (1|subjects)+(1|wave),data=df_trial,REML=F)

  septic_fit<-lmer(scale(pd_baseline)~EventData*t1_diagnosis*poly(scale(EventCounter),7)+
               (1|subjects)+(1|wave),data=df_trial,REML=F)

  anova(linear_fit,quadratic_fit,cubic_fit,quartic_fit,quintic_fit,sextic_fit,septic_fit)
  
  table_model_compare<-anova(linear_fit,quadratic_fit,cubic_fit)
  
  table_model_compare<-cbind(c('linear fit','quadratic fit','cubic fit','qaurtic fit','quintic fit'),table_model_compare)
  
  table_formatted<-table_model_compare %>%
  kbl(caption = "Model comparison on the linearity of trial number on stimulus-evoked pupillary response",
      col.names = c('','number of parameters','AIC','BIC','log likelihood','deviance','Chi-squared','df','p-value'),
      row.names = F) %>%
  kable_classic(full_width = F, html_font = "Cambria")

table_formatted

save_kable(table_formatted, file=paste0(project_path,'/output/supplements/table_modelcomparison_linearity_trialnumber_onBPS.html'))
  
  
```


## intraclass correaltion of the dependent variables

```{r ICC_of_dependent_variables}

#select only individuals that have both waves
subjects_with_both_waves<-df_dem$subjects[df_dem$timepoints=='wave1+2']
df_trial_wave12<-df_trial[df_trial$subjects %in% subjects_with_both_waves,]

#BPS
baseline_pd_wave1<-with(df_trial_wave12[df_trial_wave12$wave=='wave1',],aggregate(pd_baseline,by=list(subjects),FUN=mean,na.rm=T))
baseline_pd_wave2<-with(df_trial_wave12[df_trial_wave12$wave=='wave2',],aggregate(pd_baseline,by=list(subjects),FUN=mean,na.rm=T))
names(baseline_pd_wave1)<-c('subjects','wave1')
names(baseline_pd_wave2)<-c('subjects','wave2')

baseline_pd_waves<-merge(baseline_pd_wave1,baseline_pd_wave2,by='subjects')

cor.test(baseline_pd_waves$wave1,baseline_pd_waves$wave2)

psych::ICC(baseline_pd_waves[,-1])
###--> ICC: 0.88 [0.81, 0.93]


#SEPR
rpd204_wave1<-with(df_trial_wave12[df_trial_wave12$EventData=='204' & df_trial_wave12$wave=='wave1',],aggregate(rpd_auc.204,by=list(subjects),FUN=mean,na.rm=T))
rpd204_wave2<-with(df_trial_wave12[df_trial_wave12$EventData=='204' & df_trial_wave12$wave=='wave2',],aggregate(rpd_auc.204,by=list(subjects),FUN=mean,na.rm=T))

names(rpd204_wave1)<-c('subjects','wave1')
names(rpd204_wave2)<-c('subjects','wave2')

rpd_waves<-merge(rpd204_wave1,rpd204_wave2,by='subjects')

cor.test(rpd_waves$wave1,rpd_waves$wave2)
##--> r =.23

psych::ICC(rpd_waves[,-1])
###--> ICC: 0.37 [-0.01, 0.60]


names(df_timepoint)

#NG
gain_wave1<-with(df_timepoint[df_timepoint$wave=='wave1',],aggregate(gain_pcdm,by=list(subjects),FUN=mean,na.rm=T))
gain_wave2<-with(df_timepoint[df_timepoint$wave=='wave2',],aggregate(gain_pcdm,by=list(subjects),FUN=mean,na.rm=T))

names(gain_wave1)<-c('subjects','wave1')
names(gain_wave2)<-c('subjects','wave2')

gain_waves<-merge(gain_wave1,gain_wave2,by='subjects')

cor.test(gain_waves$wave1,gain_waves$wave2)
##--> r =.23

psych::ICC(gain_waves[,-1])
###--> ICC: 0.37 [0.02, 0.59]

```




